// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// slope
double slope(NumericVector timeIn, NumericVector ampIn, int ii, int n);
RcppExport SEXP _ItoGaussPlot_slope(SEXP timeInSEXP, SEXP ampInSEXP, SEXP iiSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type timeIn(timeInSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ampIn(ampInSEXP);
    Rcpp::traits::input_parameter< int >::type ii(iiSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(slope(timeIn, ampIn, ii, n));
    return rcpp_result_gen;
END_RCPP
}
// varSlope
double varSlope(NumericVector timeIn, NumericVector ampIn, int n, int N);
RcppExport SEXP _ItoGaussPlot_varSlope(SEXP timeInSEXP, SEXP ampInSEXP, SEXP nSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type timeIn(timeInSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ampIn(ampInSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(varSlope(timeIn, ampIn, n, N));
    return rcpp_result_gen;
END_RCPP
}
// varSlopeNU
double varSlopeNU(NumericVector timeIn, NumericVector ampIn, double windowLength, int N);
RcppExport SEXP _ItoGaussPlot_varSlopeNU(SEXP timeInSEXP, SEXP ampInSEXP, SEXP windowLengthSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type timeIn(timeInSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ampIn(ampInSEXP);
    Rcpp::traits::input_parameter< double >::type windowLength(windowLengthSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(varSlopeNU(timeIn, ampIn, windowLength, N));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ItoGaussPlot_slope", (DL_FUNC) &_ItoGaussPlot_slope, 4},
    {"_ItoGaussPlot_varSlope", (DL_FUNC) &_ItoGaussPlot_varSlope, 4},
    {"_ItoGaussPlot_varSlopeNU", (DL_FUNC) &_ItoGaussPlot_varSlopeNU, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ItoGaussPlot(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
