# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call('_ItoGaussPlot_timesTwo', PACKAGE = 'ItoGaussPlot', x)
}

muRcpp <- function(x) {
    .Call('_ItoGaussPlot_muRcpp', PACKAGE = 'ItoGaussPlot', x)
}

varRcpp <- function(x) {
    .Call('_ItoGaussPlot_varRcpp', PACKAGE = 'ItoGaussPlot', x)
}

varRcpp2 <- function(x, a, bias = TRUE) {
    .Call('_ItoGaussPlot_varRcpp2', PACKAGE = 'ItoGaussPlot', x, a, bias)
}

slope <- function(timeIn, ampIn, ii, n) {
    .Call('_ItoGaussPlot_slope', PACKAGE = 'ItoGaussPlot', timeIn, ampIn, ii, n)
}

varSlope <- function(timeIn, ampIn, n, N) {
    .Call('_ItoGaussPlot_varSlope', PACKAGE = 'ItoGaussPlot', timeIn, ampIn, n, N)
}

