# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

slope <- function(timeIn, ampIn, ii, n) {
    .Call('_ItoGaussPlot_slope', PACKAGE = 'ItoGaussPlot', timeIn, ampIn, ii, n)
}

varSlope <- function(timeIn, ampIn, n, N) {
    .Call('_ItoGaussPlot_varSlope', PACKAGE = 'ItoGaussPlot', timeIn, ampIn, n, N)
}

varSlopeNU <- function(timeIn, ampIn, windowLength, N) {
    .Call('_ItoGaussPlot_varSlopeNU', PACKAGE = 'ItoGaussPlot', timeIn, ampIn, windowLength, N)
}

